apiVersion: v1
kind: Secret
metadata:
  name: deployment-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/cbn-targit/argo-bootcamp.git
  project: instavote
