apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service.yaml
- preview-service.yaml
images:
- name: schoolofdevops/vote
  newName: git.norspang.dk/norspang/vote
  newTag: "6840380"
